name: log_chamber
description: A logging tool for Flutter applications that acts like a console window that can be seen inside the app.
version: 1.1.1
# repository: https://github.com/my_org/my_repo
repository: https://github.com/al4nnw/chamber
environment:
  sdk: ^3.2.3

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter
  # path: ^1.8.0

# This package supports all platforms listed below.
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^2.1.0
  test: ^1.24.0

flutter:
  assets:
    - assets/l10n/en.json
    - assets/l10n/es.json
    - assets/l10n/pt.json
    - assets/l10n/zh.json
